import { UTASentinelScenario } from '@/types/domain';

export const UTA_SENTINEL_SCENARIOS: UTASentinelScenario[] = [
  {
    id: 'scen-uta-01',
    title: 'High-Impact Stress Event: rNVDA EU Export Restriction',
    subtitle: 'Fundamental Overnight Catalyst Shocks Margin Buffer into CAUTION Zone',
    description:
      'A credible overnight news wire reports unexpected EU regulatory AI chip export restrictions on NVIDIA. Demonstrates how an overnight rToken fundamental price drop erodes simulated collateral value supporting an active BTCUSDT futures position.',
    isHighImpact: true,
    event: {
      id: 'evt-uta-nvda-01',
      title: 'EU Unveils Preliminary AI Export Restrictions Targeting High-Performance GPUs',
      source: 'Reuters Financial Wire',
      timestamp: new Date().toISOString(),
      category: 'POLICY',
      affectedSymbol: 'rNVDA',
      impactScore: -8.5,
      rawSnippet: 'EU Antitrust Commission proposes strict export permits on high-density AI accelerators.',
      isDemoData: true,
    },
    rTokenPosition: {
      symbol: 'rNVDA',
      name: 'NVIDIA Tokenized Equity',
      quantityTokens: 200,
      markPriceUsd: 130.0,
      haircutPct: 20, // 20% haircut = 80% collateral ratio
      collateralRatioPct: 80,
    },
    usdtCash: {
      amountUsd: 5000,
    },
    futuresPosition: {
      symbol: 'BTCUSDT Perpetual',
      positionSizeUsd: 100000,
      leverageX: 10,
      maintenanceMarginReqUsd: 15000,
    },
    policyConfig: {
      policyVersion: 'UTA-POLICY-v1.4',
      scenarioAssumptionsVersion: 'ILLUSTRATIVE-ASSUMPTIONS-2026.1',
      illustrativeHaircutPct: 20,
      illustrativeCollateralRatioPct: 80,
      cautionCoverageThreshold: 2.0,
      criticalCoverageThreshold: 1.3,
    },
    expectedBufferStatus: 'CAUTION',
    expectedRecommendation: 'REDUCE_FUTURES_RISK',
  },
  {
    id: 'scen-uta-02',
    title: 'Low-Credibility Noise Event: Unverified Social Media Rumor',
    subtitle: 'Noctive Refuses to Create False Urgency on Speculative Noise',
    description:
      'An unverified social media rumor claims minor battery tech delays. Demonstrates that Noctive accurately filters out low-credibility noise, preserving margin buffer classification as HEALTHY without forcing unnecessary deleveraging.',
    isHighImpact: false,
    event: {
      id: 'evt-uta-tsla-02',
      title: 'Unverified Social Media Post Claims Battery Cell Density Variance',
      source: 'Social Feed Noise Filter',
      timestamp: new Date().toISOString(),
      category: 'NOISE',
      affectedSymbol: 'rTSLA',
      impactScore: -1.2,
      rawSnippet: 'Anonymous post alleges minor production pause without official Tesla confirmation.',
      isDemoData: true,
    },
    rTokenPosition: {
      symbol: 'rTSLA',
      name: 'Tesla Tokenized Equity',
      quantityTokens: 150,
      markPriceUsd: 220.0,
      haircutPct: 20,
      collateralRatioPct: 80,
    },
    usdtCash: {
      amountUsd: 10000,
    },
    futuresPosition: {
      symbol: 'ETHUSDT Perpetual',
      positionSizeUsd: 60000,
      leverageX: 5,
      maintenanceMarginReqUsd: 6000,
    },
    policyConfig: {
      policyVersion: 'UTA-POLICY-v1.4',
      scenarioAssumptionsVersion: 'ILLUSTRATIVE-ASSUMPTIONS-2026.1',
      illustrativeHaircutPct: 20,
      illustrativeCollateralRatioPct: 80,
      cautionCoverageThreshold: 2.0,
      criticalCoverageThreshold: 1.3,
    },
    expectedBufferStatus: 'HEALTHY',
    expectedRecommendation: 'HOLD_MONITOR',
  },
  {
    id: 'scen-uta-03',
    title: 'Severe Crisis Scenario: Global Legal Ban & Fine',
    subtitle: 'Critical Deficit Breaches Liquidation Threshold Requiring Immediate Stand-Down',
    description:
      'High-severity antitrust fine and operational injunction against Apple. Illustrates how a catastrophic overnight rToken shock breaches critical margin coverage (< 1.3x), triggering emergency stand-down recommendations to protect collateral balance.',
    isHighImpact: true,
    event: {
      id: 'evt-uta-aapl-03',
      title: 'Global Antitrust Commission Issues $4.2B Penalty and Operational Injunction',
      source: 'Bloomberg Regulatory Wire',
      timestamp: new Date().toISOString(),
      category: 'LEGAL',
      affectedSymbol: 'rAAPL',
      impactScore: -9.5,
      rawSnippet: 'Regulators mandate multi-region store opening and levy heavy fiscal fine.',
      isDemoData: true,
    },
    rTokenPosition: {
      symbol: 'rAAPL',
      name: 'Apple Tokenized Equity',
      quantityTokens: 300,
      markPriceUsd: 180.0,
      haircutPct: 20,
      collateralRatioPct: 80,
    },
    usdtCash: {
      amountUsd: 2000,
    },
    futuresPosition: {
      symbol: 'BTCUSDT Perpetual',
      positionSizeUsd: 250000,
      leverageX: 10,
      maintenanceMarginReqUsd: 35000,
    },
    policyConfig: {
      policyVersion: 'UTA-POLICY-v1.4',
      scenarioAssumptionsVersion: 'ILLUSTRATIVE-ASSUMPTIONS-2026.1',
      illustrativeHaircutPct: 20,
      illustrativeCollateralRatioPct: 80,
      cautionCoverageThreshold: 2.0,
      criticalCoverageThreshold: 1.3,
    },
    expectedBufferStatus: 'CRITICAL',
    expectedRecommendation: 'PROTECT_MARGIN_STAND_DOWN',
  },
];
